# Please use an online yaml validator
# There is a lot more customization that you can do. You have to read the doumentation for that.

HairLengths:
  - Dashes: 0
    Length: 4
  - Dashes: 1
    Length: 4
  - Dashes: 2
    Length: 4

HairColors:
  - Dashes: 0
    Color: "22223F"
  - Dashes: 1
    Color: "22223F"
  - Dashes: 2
    Color: "22223F"

HairFlash: true # Enables the distracting white flash that happens when your dash count changes.
OutlineColor: "040000" # This specifies the hair outline color, not the sprite outline.
