# Please use an online yaml validator
# There is a lot more customization that you can do. You have to read the doumentation for that.

HairAttrWithDashes:
  - Dashes: 0
    Color: "22223F"
    Scale: 0.2, 0.2
    Length: 4
    SegmentAttrs:
      - Segment: 0
        Color: "5B6EE1"
  - Dashes: 1
    Color: "22223F"
    Scale: 0.2, 0.2
    Length: 4
    SegmentAttrs:
      - Segment: 0
        Color: "5B6EE1"
  - Dashes: 2
    Color: "22223F"
    Scale: 0.2, 0.2
    Length: 4
    SegmentAttrs:
      - Segment: 0
        Color: "5B6EE1"

HairFlash: true # Enables the distracting white flash that happens when your dash count changes.
OutlineColor: "040000" # This specifies the hair outline color, not the sprite outline.
